### ISSUE TITLE
mbsp stops functioning when another player joins the server

### ISSUE THREAD

**Issue by JamesW-webdev** [IllyaMoskvin/tes3mp-mbsp#3]
The script works perfectly fine when I've started the server, and then connected to it. When another player connects, spells stop refunding magicka for me, the script doesn't log anything to the window or the text file that I can look at or attach to this issue. The player who has joined, can cast ONE spell, and the script will work for them, but then never again for either of us. If there's any more information I can add to this that would be of help to you, please let me know. I am using ncgd and LevelingFramework as well.

**Comment by JamesW-webdev** [comment]
Closing this issue, LevelingFramework is the cause of this behavior, and I would have known that if I tested that before writing this. That's on me, sorry!

**Comment by IllyaMoskvin** [comment]
No worries, thanks for the follow-up!
